name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Luna/Luna.csproj --no-restore --configuration Release
#    - name: Test
#      run: dotnet test Luna/Luna.csproj --no-build --verbosity normal
    - name: Publish
      run: dotnet publish Luna/Luna.csproj --configuration Release --framework net6.0-windows --output Luna/bin/Release/net6.0-windows/win10-x64/publish/ --runtime win10-x64 --self-contained true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.0
      if: !failure()
      with:
        name: Luna-net6.0-windows-win10-x64
        path: Luna/bin/Release/net6.0-windows/win10-x64/publish/
        retention-days: 30
